image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - yarn install
    - yarn add -D esbuild
    - yarn test
    - yarn lint
    - yarn build-all
